### PR TITLE
Add support for file:// protocol in plugin URI

### PR DESCRIPTION
**Pull request by gcuisinier**
Allow to install plugin from local folder with the file:// format, linked to #365 

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Refactored the PluginManager.downloadToFile function to add condition on the URL format to manage HTTPs/HTTP and file protocol.
Extract the current http fetch into a dedicated internal function.

### CODE REVIEW

**Review by timja — APPROVED** [review]
Looks fine just needs checkstyle issues sorted

**Comment by gcuisinier** [comment]
👍
I've to check where I can find the detail  of checkstyle issue to fix them

**Comment by timja** [comment]
https://ci.jenkins.io/job/Tools/job/plugin-installation-manager-tool/job/PR-399/2/checkstyle/

**Comment by timja** [comment]
This failed when releasing with two spotbugs errors, not sure why it didn't show up initially, are you able to take a look?
https://github.com/jenkinsci/plugin-installation-manager-tool/runs/4665728379

**Comment by gcuisinier** [comment]
Sure! I will check

**Comment by gcuisinier** [comment]
Both issue are complaint about the fact that we are trying to use a URL ( http or file ) that's  created from an user parameter... and so unsafe.

But for the first (http), it was already present, but in another function (as I just extracted the code to a new function).
For the second, it's about the usage of File from the input param also.

For me there are both false positive, as that's the expected behaviour no?

**Comment by timja** [comment]
yes you can create a PR to suppress it then

**Comment by gcuisinier** [comment]
Done here : https://github.com/jenkinsci/plugin-installation-manager-tool/pull/400

**Pull request merged**
