### PR TITLE
[WIP] Determine all plugin dependencies before downloading

### PR DESCRIPTION
**Pull request by stopalopa**
Still a work in progress. Planning on additionally adding CLI options. 

https://issues.jenkins-ci.org/browse/JENKINS-58191

### CODE REVIEW

**Comment by kwhetstone** [comment]
I think that a few of the recently added PRs will help this one.  Do you think that you can make progress on this due to those changes?  You might even have most of this done already with the plugin-versions json file parsing.

**Comment by stopalopa** [comment]
Yes, I agree. It seems like Alex is still running into issues with the latest alpha release on Docker, so I can start working on this one today after I figure out what's going on with that.

**Comment by stopalopa** [comment]
I tried rebasing this and it was a huge mess. I'm going to create a new branch and copy in the changes I want and open a new PR.

**Comment by stopalopa** [comment]
Copied over work to another PR: https://github.com/jenkinsci/plugin-installation-manager-tool/pull/44

**Pull request closed without merging**
