### PR TITLE
[JENKINS-59173] Fix JDK 11 support

### PR DESCRIPTION
**Pull request by slide**
@PrepareForTest when used on some of the classes
will cause an issue because those classes are mocks.

JDK 8 doesn't have an issue with private fields/methods,
but JDK 11 does. Adding the @PrepareForTest annotation
to the specific test method that was failing only makes the
classes listed mocks.

### CODE REVIEW

**Comment by timja** [comment]
@slide I resubmitted your PR as a 'trusted' user here: https://github.com/jenkinsci/plugin-installation-manager-tool/pull/77

It failed on javadoc issues for java 11

**Comment by slide** [comment]
@timja I updated this PR with a fix for the javadoc, do you want to pull it into your PR?

**Comment by slide** [comment]
Another option is I can add myself as a committer on this repo via the ircbot, but I would want explicit permission from @stopalopa and other contributors.

**Comment by timja** [comment]
+1 from me on you joining

**Comment by timja** [comment]
It failed again, I think for this reason,
https://bugs.openjdk.java.net/browse/JDK-8212233

**Comment by slide** [comment]
Close and reopen to get the Jenkinsfile changes in this PR

**Pull request merged**
