### PR TITLE
Fix jenkins UC url for version specific UC

### PR DESCRIPTION
**Pull request by timja**
Fix 1 minute lag time when running the tool...

### CODE REVIEW

**Comment by stopalopa** [comment]
Do you know why that's faster? I thought that underneath the hood the "+" operator was converted to a StringBuilder.

**Comment by timja** [comment]
The reason it is faster is that before it was using this url:
```
https://updates.jenkins.io2.182
```
now it uses this
```
https://updates.jenkins.io/2.182
```

The format change was just to make it easier to read

**Comment by stopalopa** [comment]
Ohh ok. Do you think I should change all of the StringBuilders to '+' for readability?  From what I've read online StringBuilder is faster, but it might not matter that much for small strings/strings not built in a loop.

**Comment by timja** [comment]
There's only one other in the project and its in the tests, so no need

**Pull request merged**
