### PR TITLE
[JENKINS-57971] Fix compile issue and README

### PR DESCRIPTION
**Pull request by stopalopa**
Update README to include new defaults, update reference to old variable name

https://issues.jenkins-ci.org/browse/JENKINS-57971

### CODE REVIEW

**Comment by stopalopa** [comment]
I noticed that in some other code I was reading, they did not assume that System.getProperty always returned a value so I think I should probably add a check for this too:

String osName = System.getProperty("os.name");
        if(osName != null && osName.toLowerCase().contains("windows")) 

If System.getProperty("os.name") returns null, how should my code handle this?

**Comment by timja** [comment]
> I noticed that in some other code I was reading, they did not assume that System.getProperty always returned a value so I think I should probably add a check for this too when checking the OS to set the default war and plugin dir locations:
> 
> String osName = System.getProperty("os.name");
> if(osName != null && osName.toLowerCase().contains("windows"))
> 
> If System.getProperty("os.name") returns null, how should my code handle this?

`os.name` will always return a value...
https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html

**Comment by stopalopa** [comment]
I guess I didn't mean that it could return *no* value, but it could return null. Right now I'm setting the default war and plugin dir based on os.name. 

https://github.com/jenkinsci/plugin-installation-manager-tool/blob/master/plugin-management-library/src/main/java/io/jenkins/tools/pluginmanager/config/Settings.java#L25

**Comment by timja** [comment]
I've never heard of that being unset, 99% sure it is mandated to be available.
YAGNI for now

**Pull request merged**
