### PR TITLE
[no merge] Fix incrementals

### PR DESCRIPTION
**Pull request by timja**

### CODE REVIEW

**Comment by kwhetstone** [comment]
Interesting that could throw all the results?

**Comment by timja** [comment]
just trying to reverse engineer atm, basically it's not getting archived to the right path properly. already merged the PR that fixed the build

**Comment by kwhetstone** [comment]
Is this good to merge here?  Is this only publishing the poms?

**Comment by timja** [comment]
Not yet, I'll try fix tonight

**Comment by stopalopa** [comment]
Thanks, @timja!

**Pull request merged**
