### PR TITLE
Use JENKINS_UC_DOWNLOAD_URL if provided

### PR DESCRIPTION
**Pull request by nhojpatrick**
Fixes https://github.com/jenkinsci/plugin-installation-manager-tool/issues/415

The current code ignores JENKINS_UC_DOWNLOAD_URL if specified, as logic above will always result in something else being checked. Other if/else statements might also need to be changed to fix other issues with that logic.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by timja — APPROVED** [review]
I think ok

**Comment by timja** [comment]
can you take a look at the tests?

**Comment by nhojpatrick** [comment]
> can you take a look at the tests?

Happy too, I've no time until weekend probably but will be looking at them then. Wanted to get it raised and review then fix tests.

**Comment by nhojpatrick** [comment]
I've found time.
To make testing easier I've added JUnit v5 and assertAll to all errors show.
I've updated so if you define `JENKINS_UC_DOWNLOAD_URL` it's used for everything, so a true global override.

**Comment by nhojpatrick** [comment]
Converting to draft and rebase from PR https://github.com/jenkinsci/plugin-installation-manager-tool/pull/417 so this PR easier to understand what has changed when using assertAll to improve dev/test cycles.

**Review by julien-demaziere — APPROVED** [review]
LGTM
I ran the tests successfully on my PC with java 11

**Comment by sichapman** [comment]
Any chance of having this merged? Being able to use JENKINS_UC_DOWNLOAD_URL the way it is documented would be extremely useful

**Comment by MarkEWaite** [comment]
Thanks very much @timja !  Will the jar file be published to the GitHub release automatically or is there some other step needed?

**Comment by timja** [comment]
It will be I got distracted and didn't publish the release at the time, it should be attached here soon: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.13.1

**Comment by MarkEWaite** [comment]
> It will be I got distracted and didn't publish the release at the time, it should be attached here soon: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.13.1

Thanks.  I could have published that GitHub release page myself and that would have solved it.  I didn't even think of that.  Sorry that I didn't do my part to help!  Thanks for doing the release!

**Comment by cronik** [comment]
This change breaks all current usages where there is a plugin specific url defined in the plugin spec. it make more sense for the precedence to prefer the plugin url then use the download url if available?

**Pull request merged**
