### PR TITLE
Improve traceability of plugin dependency exception by printing

### LINKED ISSUE #302: Expose originally requested plugin name for message "Unable to find plugin xxx in update center yyy"
The error message should expose which plugin triggered this (usually this is a transitive dependency of a requested plugin) to be able to fix it by removing/updating the originator.

The error can be reproduced via 

`java -jar plugin-management-cli/target/jenkins-plugin-manager-2.8.x-SNAPSHOT.jar  --plugins checkstyle:4.0.0 -d plugins/ --war ~/Downloads/jenkins.war`

```
Multiple plugin prerequisites not met:
Unable to find plugin analysis-core in update center https://updates.jenkins.io/update-center.json
```

Also `ci-game:1.26` is affected:
```
Unable to find plugin findbugs in update center https://updates.jenkins.io/update-center.json
```

### PR DESCRIPTION
**Pull request by kwin**
dependency chain

This closes #302

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by timja** [comment]
No test updates required? 

Can you show actual output and testing instruction for a one-off test?

**Comment by kwin** [comment]
You can now check out with `java -jar plugin-management-cli/target/jenkins-plugin-manager-2.8.1-SNAPSHOT.jar  --plugins nabaztag:1.9 -d plugins/ --war ~/Downloads/jenkins.war --credentials abcd:acd:acd` and it exposes now

```
Multiple plugin prerequisites not met:
Plugin nabaztag:1.9 Could not resolve dependencies: null
```

**Comment by timja** [comment]
> You can now check out with `java -jar plugin-management-cli/target/jenkins-plugin-manager-2.8.1-SNAPSHOT.jar --plugins nabaztag:1.9 -d plugins/ --war ~/Downloads/jenkins.war --credentials abcd:acd:acd` and it exposes now
> 
> ```
> Multiple plugin prerequisites not met:
> Plugin nabaztag:1.9 Could not resolve dependencies: null
> ```

Is this correct?

> Multiple plugin prerequisites not met

isn't that only one?

**Comment by kwin** [comment]
Yes, but this behaviour has not changed by this PR. I will try to improve the message.

**Review by timja — APPROVED** [review]

**Pull request merged**
